language: java
jdk:
- oraclejdk8
notifications:
  email: false
env:
  global:
    secure: aou3sLNpe4Iko5O7zbjQlMn6zzRlxUwVIU0AxpU4xmK8dCt78YwfqRBPczxeVDgla0fWOJRIt4/e/yohGoIirVWHftiCL18p4Mx21eAMKd9zt0+H+aiSf6z45GcN6yLKwAkmc9LokOxzgQP0V07tVIRVytzd2X8xO9dkIk8u9KJKJ/xC0MIRpTFLE2qZQ3ZZz4IIhSPVGNECFXreq3n7M0FO18gvmM0KbR7McUyOzdOMl129PFZj2oNd1JlfJk6TjcKkr3i+K7VRQD3T/YA4BFPIhTPAV6A003RAbZArgEBEq0LDdrKAaSTe2dK3fwr+8gMu6fo+tc9Mmc4FHZEpM3aOXV/QwDL29FSOhLcKWubdBEcd3XdEmX0tfb7nHxPqpbRBUBI5pyz9x5n77tRhoDiTrOzAU6nsj3+LPcI5XtaWdCfUGnYceVxGZedS3vhFiVrqRaiVL/rNlhWYkOQ2Ro9zJSOuaUCXzEfycKKevigOw5mphR4w4Oh9+LCfAKk7Ix/Y6pzAGWB1mLY2k5pVJms9Opx7Bmt6tkOMnno5MH+LQIAdlioy+/U0Ogd+tkBdUUR5cKuDSc4HokBJ0IiMCLJ4BRVrWLtkfcQ330KZ3BEwH2jNfnQJ+HbmUYtAY8+nqfoDABUnnQRhUPTsmkhJK06Pt/lX2OFMgVyzk+yKXhQ=
